---
- hosts: loadbalancer
  sudo: yes
  tasks:
  - name: install apache
    apt: name=apache2 state=latest
  - name: install mod jk
    apt: name=libapache2-mod-jk state=latest
  - name: configure mod jk
    template: src=/ansible/template/loadbalancer/jk.conf.j2 dest=/etc/apache2/mods-available/jk.conf owner=root group=root mode=0644
    notify:
    - restart apache
  - name: configure workers
    template: src=/ansible/template/loadbalancer/workers.properties.j2 dest=/etc/libapache2-mod-jk/workers.properties owner=root group=root mode=0644
    notify:
    - restart apache
  - name: service appache started
    service: name=apache2 state=started
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
