---
- hosts: loadbalancer
  sudo: yes
  tasks:
  - name: install apache
    apt: name=apache2 state=latest
  - name: install mod jk
    apt: name=libapache2-mod-jk state=latest
  - name: configure mod jk
    setup: webserver
    template: src=/ansible/template/webserver/workers.properties.j2 dest=/etc/libapache2-mod-jk/workers.properties
    template: src=/ansible/template/webserver/server.xml.j2 dest=/etc/tomcat7/server.xml owner=root group=tomcat7 mode=0644
    notify:
    - restart apache
  - name: service appache started
    service: name=apache2 state=started
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
