---
# file: roles/pxe/tasks/main.yml

- name: configure hosts
  su: yes
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=644

- name: install dnsmasq
  su: yes
  apt: name=dnsmasq state=present

- name: install debian image
  su: yes
  unarchive: src=netboot.tar.gz copy=yes dest=/var/ftpd

- name: configure preseed url
  su: yes
  copy: src=txt.cfg dest=/var/ftpd/debian-installer/amd64/boot-screens/txt.cfg owner=root group=root mode=644

- name: configure dnsmasq
  su: yes
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf owner=root group=root mode=644
  notify:
    - restart dnsmasq

- name: run dnsmasq
  su: yes
  service: name=dnsmasq state=running enabled=yes
  
- name: install nginx 
  su: yes
  apt: name=nginx-light  state=present

- name: run nginx
  su: yes
  service: name=nginx state=running enabled=yes

- name: install preseed
  su: yes
  copy: src=preseed.txt dest=/var/www/html/preseed.txt owner=root group=root mode=644
