---
- name: install haproxy
  apt: name=haproxy
  sudo: yes

- name: configure haproxy
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  sudo: yes
  notify:
    - restart haproxy

- name: run haproxy
  service: name=haproxy state=started
  sudo: yes
