---
- name: install ntp
  apt: name=ntp state=installed
  su: yes
  tags: ntp

- name: configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
  su: yes
  notify:
    - restart ntp
  tags: ntp

- name: start service ntp
  service: name=ntp state=started
  su: yes
  tags: ntp

- name: install htop
  su: yes
  apt: name=htop state=installed
  tags: htop
