---
- name: install java
  apt: name=default-jdk
  sudo: yes

- name: install tomcat
  apt: name=tomcat8
  sudo: yes

- name: install admin
  apt: name=tomcat8-admin
  sudo: yes

- name: update hosts
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=0644
  notify:
  -  restart tomcat8
  sudo: yes

- name: configure tomcat
  copy: src=server.xml dest=/etc/tomcat8/server.xml owner=root group=tomcat8 mode=0644
  notify:
  - restart tomcat8
  sudo: yes

- name: configure users
  template: src=tomcat-users.xml.j2 dest=/etc/tomcat8/tomcat-users.xml owner=root group=tomcat8 mode=0644
  notify:
  - restart tomcat8
  sudo: yes

#- name: deploy probe
#  copy: src=probe.war dest=/var/lib/tomcat7/webapps/probe.war owner=root group=tomcat7 mode=0644
#  notify:
#  - restart tomcat7
#  sudo: yes

- name: deploy clusterjsp
  copy: src=clusterjsp.war dest=/var/lib/tomcat8/webapps/clusterjsp.war owner=root group=tomcat8 mode=0644
  sudo: yes
#  notify:
#  - restart tomcat8
#  sudo: yes 

- name: run tomcat8 service
  service: name=tomcat8 state=started
  sudo: yes
